SSP test: putting clone settings in a context manager block
SSP tests were failing with:

ERROR: Cannot modify case, read_only. Case must be opened with read_only=False and can only be modified within a context manager

This change solves the problem.

Regarding the settings made on `self._case` (various
`self._case.set_value(...)` calls): Initially, I thought I'd also need
to put those in a `with self._case` block (removing
`self._case.flush()`), but looking at some examples (e.g., eri.py), it
looks like these context manager blocks are mainly just used for the
clone, not for `self._case`. Jim Foucar pointed out that you don't need
a `with` block if the given case has already been opened higher up in
the call stack, which is presumably the situation here.