Run subset_data if outputs don't exist.
It seems like build_phase() gets called at least once before sharedlib_only=True, because before this commit I was getting this error:

    ERROR: Command /glade/work/samrabin/ctsm_subsetdata-systemtest/bld/build-namelist failed rc=255
    out=
    err=Attempt to call undefined import method with arguments ("main") via package "CLMBuildNamelist" (Perhaps you forgot to load the package?) at /glade/work/samrabin/ctsm_subsetdata-systemtest/bld/build-namelist line 21.
    ERROR : CLM build-namelist::CLMBuildNamelist::add_default() : No default value found for fsurdat.
                Are defaults provided for this resolution and land mask?