Successfully removed two more restart variables
qflx_snofrz_lyr and sminn_to_plant_fun_patch

Abbreviated standard testing: PASS

Unabbreviated standard testing: OK

This test gave an error unrelated to the removal of restart variables:
DAE_N2_D_Lh12.f10_f10_musgs.I2000Clm50BgcCropGs.cheyenne_intel.clm-DA_multidrv in 3.746383 seconds (FAIL)
    Case dir: /glade/scratch/slevis/DAE_N2_D_Lh12.f10_f10_musgs.I2000Clm50BgcCropGs.cheyenne_intel.clm-DA_multidrv.C.20190112_132222_8wl8c7
    Errors were:
        Model clm missing file finidat = '/glade/p_old/image/RDA_strawman/CESM_ensembles/CLM/CLM5BGC-Crop/ctsm_2001-01-01-00000/clm5_f09_spinup80.clm2_0001.r.2001-01-01-00000.nc'
        Model clm missing file finidat = '/glade/p_old/image/RDA_strawman/CESM_ensembles/CLM/CLM5BGC-Crop/ctsm_2001-01-01-00000/clm5_f09_spinup80.clm2_0002.r.2001-01-01-00000.nc'
        Client protocol gftp not enabled
        Model clm missing file finidat = '/glade/p_old/image/RDA_strawman/CESM_ensembles/CLM/CLM5BGC-Crop/ctsm_2001-01-01-00000/clm5_f09_spinup80.clm2_0001.r.2001-01-01-00000.nc'
            Cannot download file since it lives outside of the input_data_root '/glade/p/cesmdata/cseg/inputdata'
        Model clm missing file finidat = '/glade/p_old/image/RDA_strawman/CESM_ensembles/CLM/CLM5BGC-Crop/ctsm_2001-01-01-00000/clm5_f09_spinup80.clm2_0002.r.2001-01-01-00000.nc'
            Cannot download file since it lives outside of the input_data_root '/glade/p/cesmdata/cseg/inputdata'
        Model clm missing file finidat = '/glade/p_old/image/RDA_strawman/CESM_ensembles/CLM/CLM5BGC-Crop/ctsm_2001-01-01-00000/clm5_f09_spinup80.clm2_0001.r.2001-01-01-00000.nc'
            Cannot download file since it lives outside of the input_data_root '/glade/p/cesmdata/cseg/inputdata'
        Model clm missing file finidat = '/glade/p_old/image/RDA_strawman/CESM_ensembles/CLM/CLM5BGC-Crop/ctsm_2001-01-01-00000/clm5_f09_spinup80.clm2_0002.r.2001-01-01-00000.nc'
            Cannot download file since it lives outside of the input_data_root '/glade/p/cesmdata/cseg/inputdata'
        Model clm missing file finidat = '/glade/p_old/image/RDA_strawman/CESM_ensembles/CLM/CLM5BGC-Crop/ctsm_2001-01-01-00000/clm5_f09_spinup80.clm2_0001.r.2001-01-01-00000.nc'
            Cannot download file since it lives outside of the input_data_root '/glade/p/cesmdata/cseg/inputdata'
        Model clm missing file finidat = '/glade/p_old/image/RDA_strawman/CESM_ensembles/CLM/CLM5BGC-Crop/ctsm_2001-01-01-00000/clm5_f09_spinup80.clm2_0002.r.2001-01-01-00000.nc'
            Cannot download file since it lives outside of the input_data_root '/glade/p/cesmdata/cseg/inputdata'
        Client protocol None not enabled
        ERROR: Could not find all inputdata on any server