Corrections and updates to get past certain errors
Test
SMS_Ld3_PS.f09_g17.IHistClm50BgcCrop.cheyenne_intel.clm-f09_dec1990Start_GU_LULCC
now fails with
ERROR: initVerticalStructure: zw(p,0) improperly defined