Increase some error tolerances
This global test
SMS_Ld3_D.f19_g17.I2000Clm50BgcCrop.cheyenne_intel
currently fails with this error, likely due to small ztop:

Attempting to initialize multilayer canopy vertical structure .....
ncan, p, nlevmlcan =         304           5         100
ntop, n_zref, dz_zref, zref, ztop =
11   293   29.776757   30.89297   1.116
 ENDRUN:
 ERROR:  ERROR: initVerticalStructure: ncan > nlevmlcan